format_version: v1.0
type: UniqueComponent
attributes: {id: cdac2}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CDAC_REFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
- type: ElementPosition
  attributes: {x: '520', y: '20', id: cdac2}
