format_version: v1.0
type: UniqueComponent
attributes: {id: i2c1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '295'}
  - type: Integer
    attributes: {id: I2CS_CORE_TIMER_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '60000000'}
  - type: Integer
    attributes: {id: I2CS_RISE_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '18'}
  - type: KeyValueSet
    attributes: {id: I2CS_SDAHT_SUPPORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: I2CS_SETUP_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '6'}
  - type: Integer
    attributes: {id: I2C_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '60000000'}
  - type: Long
    attributes: {id: I2C_CLOCK_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '100000'}
  - type: Long
    attributes: {id: I2C_CLOCK_SPEED_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c1, value: '100000'}
  - type: Boolean
    attributes: {id: I2C_DISSLW}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: I2C_SMEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '362', y: '19', id: i2c1}
