format_version: v1.0
type: UniqueComponent
attributes: {id: icap5}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: ICAP_ICxCON_ICI}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ICAP_ICxCON_ICTMR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: ICAP_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: ICxCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icap5, value: '1'}
- type: ElementPosition
  attributes: {x: '410', y: '295', id: icap5}
