files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 76E19C3F48BC9B1B060222E70DD3415C
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6E6FCDB2467BF8F33B94FD7D70D367B3
- generatedChecksum: F815A58CDBCB7A2D16FB75A8A7F76887
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B2A3D2B90D123C26B0ADC5299912BE11
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 6F363E46A78DE21682FC28F181BC45A7
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8024F89DA88AC5EA5D09B4F93B27A804
- generatedChecksum: 558B7D7BC49AF089E9DD2B18F3293936
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/cdac
  name: plib_cdac2.c
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 558B7D7BC49AF089E9DD2B18F3293936
- generatedChecksum: A4F4200C544E5467FC66EB7DBEABF797
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/cdac
  name: plib_cdac3.c
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: SOURCE
  userChecksum: E3C2BC64AD24EB321C81DB61FCF629FF
- generatedChecksum: 416D1CA9675AD8F47115C9F527F3F3B0
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8801BCF66761498884DF14C744A37C8D
- generatedChecksum: 7F39C16B1C4133E817985A472F51E42D
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: DDAE0A39F628E569FC7B64013302A848
- generatedChecksum: 5EDDFE5F45E25F52BBA71499BA5068E8
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5EDDFE5F45E25F52BBA71499BA5068E8
- generatedChecksum: 841387E7BFB6D2E70243B9DF11E4AEEF
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/i2c/master
  name: plib_i2c1_master.c
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E973892C352AD2EBD3E80DBB1DD8CC9
- generatedChecksum: 16D73C86E9470E881E39B2380FB0B1D9
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/icap
  name: plib_icap3.c
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16D73C86E9470E881E39B2380FB0B1D9
- generatedChecksum: 2A636FC5A017D8CAB07EAAAA2F79F02D
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/icap
  name: plib_icap4.c
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2A636FC5A017D8CAB07EAAAA2F79F02D
- generatedChecksum: 0AEFE6FD6D592C450A363C8446104668
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/icap
  name: plib_icap5.c
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0AEFE6FD6D592C450A363C8446104668
- generatedChecksum: 9B7527C46980432F20820D5A9C15D5A0
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/mcpwm
  name: plib_mcpwm.c
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64DA9B7EC80D81040D1238DAC89BD1DE
- generatedChecksum: CE70C92D4F1752E99E45B6C8BB8214DC
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/ocmp
  name: plib_ocmp2.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: CE70C92D4F1752E99E45B6C8BB8214DC
- generatedChecksum: F252F115A691939762FD5EF9723B2182
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/ocmp
  name: plib_ocmp3.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: F252F115A691939762FD5EF9723B2182
- generatedChecksum: F1021C6FAD4744F2BBAC8670A1969A43
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/ocmp
  name: plib_ocmp4.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: F1021C6FAD4744F2BBAC8670A1969A43
- generatedChecksum: CF40B34C6234CCDFC1B8AD4DC90B917D
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/qei
  name: plib_qei1.c
  physicalPath: peripheral/qei
  security: NON_SECURE
  type: SOURCE
  userChecksum: 24A18DAA6A34F7B4F1969603F1EE97ED
- generatedChecksum: 25A7B1BC671EC7591B0E40C9C19E1F39
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 25A7B1BC671EC7591B0E40C9C19E1F39
- generatedChecksum: DDFD96C1DA8AE518426991015AC5E5CB
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/tmr
  name: plib_tmr3.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 49FBA4E53A0F0E68B05F6924BB42F9F9
- generatedChecksum: 171F05807BE1DA35533DFD415B32C57E
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart6.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7C6F375C6CC8C1B995F1E5C5E5BC3B0E
- generatedChecksum: AEAD678D52A900BF13F45EFDA811BC10
  logicalPath: config/pic32mk_mcm_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: D80121758610087D2DDA64108968D633
- generatedChecksum: 6DDA7353ED4FBB687AC536FE3D56E2B0
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5EA870452299D2B26B9D7AFCF0598637
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 74058744638925EEB20F58B4328F1B68
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 8FC650F326DC1D773DBEEED9FE623089
- generatedChecksum: 9BC740B9E11F5CABC4A22BD0F7689C26
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 9BC740B9E11F5CABC4A22BD0F7689C26
- generatedChecksum: 687743D718CCAED3CDC08D86A85048A5
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/cdac
  name: plib_cdac2.h
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: HEADER
  userChecksum: 687743D718CCAED3CDC08D86A85048A5
- generatedChecksum: F80C81E37BF772B27E12AB4FAA51F92F
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/cdac
  name: plib_cdac3.h
  physicalPath: peripheral/cdac
  security: NON_SECURE
  type: HEADER
  userChecksum: F80C81E37BF772B27E12AB4FAA51F92F
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: 0EF22D41AC4B64907F5E223637035014
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 0EF22D41AC4B64907F5E223637035014
- generatedChecksum: 407D8CE5F0C091BCEBB78967FECBE53E
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/i2c/master
  name: plib_i2c1_master.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: 854008CD04D45CA25560660A95BE6964
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/i2c/master
  name: plib_i2c_master_common.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: 1C131A59E361A17381F442C2B0EACFAB
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/icap
  name: plib_icap3.h
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C131A59E361A17381F442C2B0EACFAB
- generatedChecksum: 5E65EB84AA441757736F21788C962B8E
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/icap
  name: plib_icap4.h
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: HEADER
  userChecksum: 5E65EB84AA441757736F21788C962B8E
- generatedChecksum: 1BC6545B91B9D519C02081D6352E464F
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/icap
  name: plib_icap5.h
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: HEADER
  userChecksum: 1BC6545B91B9D519C02081D6352E464F
- generatedChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/icap
  name: plib_icap_common.h
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: HEADER
  userChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
- generatedChecksum: 12CBE2439F4C4DECD2B376033BBADA45
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/mcpwm
  name: plib_mcpwm.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: F04ED49352F295B9A4D83CAB8A8BD044
- generatedChecksum: 8C0682DB8DD38F7C09771C63347D06FF
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/mcpwm
  name: plib_mcpwm_common.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0682DB8DD38F7C09771C63347D06FF
- generatedChecksum: D4D53FC969CDADF7879D485F6A7CA6C3
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/ocmp
  name: plib_ocmp2.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: D4D53FC969CDADF7879D485F6A7CA6C3
- generatedChecksum: D81929C69FED952EA343BEA2D3C48392
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/ocmp
  name: plib_ocmp3.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: D81929C69FED952EA343BEA2D3C48392
- generatedChecksum: C3B4459C39595482A48CB50EBE595C83
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/ocmp
  name: plib_ocmp4.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C3B4459C39595482A48CB50EBE595C83
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: D90CDC0EB371E38671D4FC9ACEB37291
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/qei
  name: plib_qei1.h
  physicalPath: peripheral/qei
  security: NON_SECURE
  type: HEADER
  userChecksum: D90CDC0EB371E38671D4FC9ACEB37291
- generatedChecksum: D6A76BFCD1B06AC07959D1D4CB4D2B3E
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/qei
  name: plib_qei_common.h
  physicalPath: peripheral/qei
  security: NON_SECURE
  type: HEADER
  userChecksum: D6A76BFCD1B06AC07959D1D4CB4D2B3E
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: BF06638282DB46493859AC9C1A145999
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/tmr
  name: plib_tmr3.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 0724D7315223CF9CC54A8172113EC43C
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart6.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: F3783227CE3257C204E5AAC0C922B337
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 0D025660A81D3BAE5CC13F9B622DECFA
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 0D025660A81D3BAE5CC13F9B622DECFA
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
