format_version: v1.0
type: UniqueComponent
attributes: {id: qei1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: QEI1_PositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: QEI1_PositionCountSet}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: QEI1_VelocityGet}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: QEI1_VelocityCountSet}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: QEI1_Start}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: QEI1_Stop}
  - type: Long
    attributes: {id: QEI1CMPL__CMPL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: QEI1CON__PIMOD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Long
    attributes: {id: QEI1ICC__ICCH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '200'}
  - type: KeyValueSet
    attributes: {id: QEI1IOC__FLTREN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: QEI1STAT__HOMIEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: QEI1STAT__IDXIEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: QEI_EVIC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: '0'}
  - type: Boolean
    attributes: {id: QEI_HOME_AVAILABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: QEI_INDEX_AVAILABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Hex
    attributes: {id: QEI_QEICON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: '6144'}
  - type: Hex
    attributes: {id: QEI_QEIIOC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: '16384'}
  - type: Hex
    attributes: {id: QEI_QEISTAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei1, value: '0'}
- type: ElementPosition
  attributes: {x: '375', y: '118', id: qei1}
