configName: pic32mk_mcm_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK1024MCM100
projectName: ''
settings:
  PackageFilter: aerospace;audio;aws_cloud;bsp;bt;classb_pic32mk_mc;core;core_apps_pic32mk;crypto;cryptoauthlib;cryptoauthlib_apps;csp;csp_apps_pic32mk;dev_packs;expresslogic_threadx;gfx;gfx_apps;harmony-services;mbed_os_rtos;mbed_os_rtos_apps;mc_apps_pic32mk;mc_apps_sam_e7x_s7x_v7x;micrium_ucos3;motor_control;net;net_apps_pic32mx;net_apps_pic32mz;quick_docs;reference_apps;touch;usb;wireless;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.9.143\atdf\PIC32MK1024MCM100.atdf
